stages:

    featurize:
        cmd: python3 src/featurize.py assets/data/raw/
        deps:
            - assets/data/raw
            - src/featurize.py
            - src/config.py
        outs:
            - assets/data/featurized
            - assets/output/fingerprint_timestamps.npy
            - assets/output/combined.csv
        params:
            - featurize.dataset

    cluster:
        cmd: python3 src/cluster.py assets/data/featurized/
        deps:
            - assets/data/featurized
            - src/cluster.py
            - src/config.py
        outs:
            - assets/output/labels.csv
            - assets/output/fingerprints.csv
        params:
            - cluster.learning_method

    evaluate:
        cmd: python3 src/evaluate.py
        deps:
            - assets/data/featurized
            - assets/models/model.pkl
            - assets/output/labels.csv
            - assets/output/fingerprint_timestamps.npy
            - assets/output/combined.csv
            - src/evaluate.py
            - src/config.py
        outs:
            - assets/plots/clusters.png
            - assets/plots/labels_over_time.html
    #     metrics:
    #     - assets/metrics/metrics.json

