stages:

    featurize:
        cmd: python3 src/featurize.py assets/data/raw/
        deps:
            - assets/data/raw 
            - src/featurize.py
            - src/config.py
        outs:
            - assets/data/featurized
            - assets/output/feature_vector_timestamps.npy
            - assets/output/original_data.csv
            - assets/scalers/input_scaler.z
        params:
            - featurize.columns
            - featurize.dataset
            - featurize.overlap
            - featurize.timestamp_column
            - featurize.convert_timestamp_to_datetime
            - featurize.window_size

    train:
        cmd: python3 src/train.py assets/data/featurized/
        deps:
            - assets/data/featurized
            - assets/data/annotations
            - src/train.py
            - src/config.py
            - src/annotations.py
        outs:
            - assets/output/labels.csv
            - assets/models
        params:
            - train.learning_method
            - train.max_iter
            - train.n_clusters
            - train.use_predefined_centroids
            - train.fix_predefined_centroids
            - train.annotations_dir

    postprocess:
        cmd: python3 src/postprocess.py
        deps:
            - assets/data/featurized
            - assets/models/model.pkl
            - assets/output/labels.csv
            - assets/output/feature_vector_timestamps.npy
            - assets/output/original_data.csv
            - src/postprocess.py
            - src/config.py
        outs:
            # - assets/plots/clusters.png
            - assets/plots/labels_over_time.html
            - assets/output/cluster_names.csv
            - assets/output/event_log.csv
        params:
            - train.learning_method
            - train.max_iter
            - train.n_clusters
            - train.use_predefined_centroids
            - train.fix_predefined_centroids
            - train.annotations_dir
            - postprocess.min_segment_length
        metrics:
            - assets/metrics/metrics.json

    # llm:
    #     cmd: python3 src/explain.py
    #     deps:
    #         - src/llm.py
    #         - assets/output/cluster_names.csv
    #     params:
    #         - llm.dataset_description
