cluster:
  learning_method: minibatchkmeans
  max_iter: 100
  n_clusters: 6
evaluate: null
featurize:
  columns: Channel_4_Data
  dataset: nova10
  overlap: 0
  timestamp_column: Date
  window_size: 100
