cluster:
  annotations_dir: nova10
  fix_predefined_centroids: true
  learning_method: minibatchkmeans
  max_iter: 100
  n_clusters: 6
  use_predefined_centroids: true
evaluate: null
featurize:
  columns: Channel_4_Data
  dataset: nova10_p2_medium
  overlap: 0
  timestamp_column: ''
  window_size: 20
