cluster:
  learning_method: minibatchkmeans
  max_iter: 100
  n_clusters: 4
evaluate: null
featurize:
  columns: Spindle_Torque
  dataset: automotive_tiny
  overlap: 0
  timestamp_column: Date
  window_size: 3
