cluster:
  learning_method: minibatchkmeans
  max_iter: 100
  n_clusters: 6
evaluate: null
featurize:
  columns: Spindle_Torque
  dataset: automotive
  overlap: 0
  timestamp_column: Date
  window_size: 100
