featurize:
  columns: Channel_4_Data
  convert_timestamp_to_datetime: true
  dataset: nova10_p8_10hz-20230721121352
  overlap: 0
  timestamp_column: timestamp
  window_size: 30
postprocess:
  min_segment_length: 1
train:
  annotations_dir: nova10_p8_10hz_annotations
  fix_predefined_centroids: false
  learning_method: minibatchkmeans
  max_iter: 100
  n_clusters: 7
  use_predefined_centroids: true
