featurize:
    # dataset: profileB_combined
    # dataset: nova10_p2_medium_every_5th_row
    dataset: nova10_with_timestamps
    # window_size: 10
    window_size: 500
    # window_size: 2500
    overlap: 0
    convert_timestamp_to_datetime: True
    # timestamp_column: Date/Time
    timestamp_column: timestamp
    # columns: Stem Force
    columns: Channel_4_Data

cluster:
    learning_method: minibatchkmeans
    # n_clusters: 3
    n_clusters: 7
    max_iter: 100
    use_predefined_centroids: True
    fix_predefined_centroids: False
    # annotations_dir: benteler
    annotations_dir: nova10v2
    min_segment_length: 10

evaluate:
