cluster:
  learning_method: minibatchkmeans
  max_iter: 100
  n_clusters: 4
evaluate: null
featurize:
  columns: OP390_NC_SP_Torque
  dataset: renault_small
  overlap: 0
  timestamp_column: Date
  window_size: 100
