cluster:
  annotations_dir: null
  fix_predefined_centroids: false
  learning_method: minibatchkmeans
  max_iter: 100
  n_clusters: 7
  use_predefined_centroids: false
featurize:
  columns: power
  convert_timestamp_to_datetime: true
  dataset: rip_restructured_merged
  overlap: 0
  timestamp_column: date
  window_size: 10
postprocess:
  min_segment_length: 4
