cluster:
  annotations_dir: nova10_p8_10hz_annotations
  fix_predefined_centroids: False
  # learning_method: meanshift
  # learning_method: dbscan
  learning_method: affinitypropagation
  # learning_method: minibatchkmeans
  max_iter: 100
  min_segment_length: 0
  n_clusters: 7
  use_predefined_centroids: False
evaluate: null
featurize:
  columns: Channel_4_Data
  convert_timestamp_to_datetime: true
  dataset: nova10_p8_10hz
  overlap: 0
  timestamp_column: timestamp
  window_size: 10
