cluster:
  learning_method: minibatchkmeans
  max_iter: 100
  n_clusters: '4'
evaluate: null
featurize:
  columns: OP_390_NC_SP_Torque
  dataset: renault_sync
  overlap: 0
  timestamp_column: Timestamp
  window_size: 10
